FROM golang:1.25-alpine

RUN apk add --no-cache rsync git build-base

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /replit-sync ./cmd/replitsync

CMD ["/replit-sync"]